# Generated by Django 4.0.4 on 2022-04-29 05:35

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('img_url', models.TextField()),
                ('content', models.TextField(null=True)),
                ('uploaded_at', models.DateTimeField(blank=True, default=datetime.datetime(2022, 4, 29, 14, 35, 56, 293409))),
                ('team_id', models.ForeignKey(db_column='team_id', on_delete=django.db.models.deletion.CASCADE, related_name='team', to='account.team')),
            ],
        ),
    ]
